/// Maps TC-001 … TC-205 to implementation references for the dev harness.
///
/// Auto-verifiable = runner can check return values without UI.
/// Visual = requires human confirmation on device.
class TcDefinition {
  const TcDefinition({
    required this.id,
    required this.screen,
    required this.feature,
    required this.method,
    required this.file,
    required this.autoVerifiable,
  });

  final String id;
  final String screen;
  final String feature;
  final String method;
  final String file;
  final bool autoVerifiable;
}

/// All 205 TC definitions (generated by bucket + index).
final Map<String, TcDefinition> tcMethodMap = {
  for (final d in _buildAllTcDefinitions()) d.id: d,
};

List<TcDefinition> _buildAllTcDefinitions() {
  final out = <TcDefinition>[];
  var n = 1;

  void addRange(
    int count,
    String screen,
    String file,
    String methodPrefix,
    bool Function(int offset) auto,
    String Function(int offset) feature,
  ) {
    for (var o = 0; o < count; o++) {
      final id = 'TC-${n.toString().padLeft(3, '0')}';
      out.add(
        TcDefinition(
          id: id,
          screen: screen,
          feature: feature(o),
          method: '$methodPrefix#${o + 1}',
          file: file,
          autoVerifiable: auto(o),
        ),
      );
      n++;
    }
  }

  // TC-001–012 App shell / global
  addRange(
    12,
    'App Shell / Global',
    'lib/core/presentation/app_shell.dart',
    'shell_tc',
    (o) => o < 8,
    (o) => [
      'Bottom navigation tabs',
      'Center slot → Add Reminder',
      'FAB → Add Reminder',
      'Launch permission flow',
      'Channel disabled banner',
      'Orientation',
      'Background resume',
      'Double-tap FAB',
      'Legacy /settings redirect',
      'Alarm route bypass',
      'No REST session',
      'Local/export error analogue',
    ][o],
  );

  // TC-013–045 Onboarding (33)
  addRange(
    33,
    'Onboarding',
    'lib/features/onboarding/presentation/onboarding_page_view.dart',
    'onboarding_tc',
    (o) => o < 20,
    (o) => 'Onboarding step ${o + 1}',
  );

  // TC-046–065 Home (20)
  addRange(
    20,
    'Home',
    'lib/features/daily_schedule/presentation/home_screen.dart',
    'home_tc',
    (o) => o < 14,
    (o) => 'Home scenario ${o + 1}',
  );

  // TC-066–074 Missed sheet (9)
  addRange(
    9,
    'Missed reminders sheet',
    'lib/features/daily_schedule/presentation/missed_reminders_sheet.dart',
    'missed_tc',
    (o) => o < 5,
    (o) => 'Missed sheet ${o + 1}',
  );

  // TC-075–084 Schedule (10)
  addRange(
    10,
    "Today's schedule",
    'lib/features/daily_schedule/presentation/todays_full_schedule_screen.dart',
    'schedule_tc',
    (o) => o < 6,
    (o) => 'Schedule ${o + 1}',
  );

  // TC-085–099 History (15)
  addRange(
    15,
    'History',
    'lib/features/history/presentation/history_screen.dart',
    'history_tc',
    (o) => o < 10,
    (o) => 'History ${o + 1}',
  );

  // TC-100–125 Profile (26)
  addRange(
    26,
    'Profile / Settings',
    'lib/features/settings/presentation/settings_screen.dart',
    'profile_tc',
    (o) => o < 18,
    (o) => 'Settings ${o + 1}',
  );

  // TC-126–148 Add reminder (23)
  addRange(
    23,
    'Add Reminder',
    'lib/features/reminders/presentation/add_reminder_screen.dart',
    'add_reminder_tc',
    (o) => o < 12,
    (o) => 'Add reminder ${o + 1}',
  );

  // TC-149–158 Template library (10)
  addRange(
    10,
    'Template library',
    'lib/features/templates/presentation/template_library_screen.dart',
    'template_tc',
    (o) => o < 5,
    (o) => 'Template ${o + 1}',
  );

  // TC-159–168 Chain context (10)
  addRange(
    10,
    'Chain context',
    'lib/features/daily_schedule/presentation/chain_context_screen.dart',
    'chain_tc',
    (o) => o < 7,
    (o) => 'Chain ${o + 1}',
  );

  // TC-169–188 Alarm & tray (20)
  addRange(
    20,
    'Fullscreen alarm',
    'lib/features/escalation/presentation/alarm_screen_loader.dart',
    'alarm_tc',
    (o) => o < 11,
    (o) => 'Alarm ${o + 1}',
  );

  // TC-189–205 Kids (17)
  addRange(
    17,
    'Kids mode',
    'lib/features/kids_mode/presentation/kids_dashboard_screen.dart',
    'kids_tc',
    (o) => o < 8,
    (o) => 'Kids ${o + 1}',
  );

  if (out.length != 205) {
    throw StateError('tc_method_map: expected 205 TCs, got ${out.length}');
  }
  return out;
}
